channels:
- conda-forge
dependencies:
- python=3.12.4
- pip<=24.3.1
- pip:
  - mlflow==2.21.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.0
  - psutil==5.9.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
